name: Release
on:
  release:
    types: [created]

jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        platform:
          - { runner: windows-latest, name: windows }
          - { runner: macos-latest, name: mac }
          - { runner: ubuntu-20.04, name: linux }

    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@nightly

      - name: Build
        id: build
        run: |
          cargo build --release
          
          ext=${{ matrix.platform.name == 'windows' && '.exe' || '' }}
          
          mkdir artifacts
          mv \
            ./target/release/lunar_launcher_inject$ext \
            ./artifacts/lunar-launcher-inject-${{ matrix.platform.name }}-${{ github.event.release.name }}$ext

      - name: Upload Executable
        run: gh release upload $GITHUB_REF_NAME ./artifacts/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
